name: CDKTF Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node & Python
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install CDKTF CLI & Python dependencies
        run: |
          npm install -g cdktf-cli
          python3 -m pip install --upgrade pip
          pip install -r cdk/requirements.txt

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.6

      - name: Authenticate to GCP via Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Infrastructure
        run: |
          cd cdk
          cdktf get
          cdktf deploy --auto-approve
