name: CDKTF Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install CDKTF CLI & Python dependencies
        run: |
          npm install -g cdktf-cli
          python3 -m pip install --upgrade pip
          pip install -r cdk/requirements.txt

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up remote state bucket
        run: |
          STATE_BUCKET=ts-eras-quiz-tfstate
          PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
          if ! gcloud storage buckets describe gs://$STATE_BUCKET --project=$PROJECT_ID >/dev/null 2>&1; then
            echo "Creating remote state bucket..."
            gcloud storage buckets create gs://$STATE_BUCKET \
              --project=$PROJECT_ID \
              --location=EU \
              --default-storage-class=STANDARD
          else
            echo "Remote state bucket already exists."
          fi

      - name: Deploy Infrastructure
        run: |
          cd cdk
          cdktf get
          cdktf synth
          cdktf deploy --auto-approve
